name: calc_card_flutter
description: calc card app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.3 <3.0.0'
  flutter: '>=2.0.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.13.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.0

flutter:
  uses-material-design: true
